on:
  push:
    branches: ["main"]
name: Deploy Extension
env:
  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
  OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
jobs:
  create_env_file:
    runs-on: ubuntu-latest
    steps:
      - run: |
          touch .env
          echo OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }} >> .env
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: SpicyPizza/create-envfile@v2.0.2
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
